FROM node:latest

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm install

COPY scripts /usr/src/app/scripts
COPY config /usr/src/app/config
COPY src /usr/src/app/src
COPY public /usr/src/app/public

RUN npm run build

ADD public/index.html /usr/src/app/public/index.html

# start app
CMD ["npm", "start"]
