version: "3.2"

services:
  client:
    build:
      context: ./eppsa-mobile-game-client
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ./eppsa-mobile-game-client:/app
      - /app/node_modules

  server:
    build:
      context: ./eppsa-mobile-game-server
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    volumes:
      - ./eppsa-mobile-game-server:/app
      - /app/node_modules
