version: "3.2"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "8090:8080"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "8091:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
