version: "3.2"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
